name: "Release"

on:
  push:
    tags:
      - "v*"

env:
  RUSTFLAGS: "--cfg fetch_extended_version_info"
  CARGO_TERM_COLOR: always
  PYTHONUNBUFFERED: "1"

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Get Tag
        uses: olegtarasov/get-tag@v2.1.3
        id: version_tag
        with:
          tagRegex: "v(.*)"

  release:
    runs-on: ubuntu-24.04
    needs: [get_tag]
    steps:
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set +e
          gh release create "v${{ needs.get_tag.outputs.tag }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="v${{ needs.get_tag.outputs.tag }}" \
              --generate-notes

  docker_build:
    uses: ./.github/workflows/docker.yml
    needs: [get_tag]
    with:
      version: ${{ needs.get_tag.outputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  release-artifacts:
    needs: [get_tag]
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Get Release Upload URL
        shell: bash
        run: |
          UPLOAD_URL=$(gh release view v${{ needs.get_tag.outputs.tag }} --json uploadUrl -q '.uploadUrl' | sed 's/{.*//')
          BIN_NAME_CS="cql-stress-cassandra-stress-${{ needs.get_tag.outputs.tag }}-${{ matrix.os }}"
          BIN_NAME_SB="cql-stress-scylla-bench-${{ needs.get_tag.outputs.tag }}-${{ matrix.os }}"
          echo "BIN_NAME_CS=$BIN_NAME_CS" >> $GITHUB_ENV
          echo "BIN_NAME_CS=$BIN_NAME_CS"
          echo "BIN_NAME_SB=$BIN_NAME_SB" >> $GITHUB_ENV
          echo "BIN_NAME_SB=$BIN_NAME_SB"
          echo "UPLOAD_URL_CS=$UPLOAD_URL?name=$BIN_NAME_CS" >> $GITHUB_ENV
          echo "UPLOAD_URL_SB=$UPLOAD_URL?name=$BIN_NAME_SB" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile dist --all

      - name: Upload Release Asset
        id: upload-release-asset-cs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL_CS }}
          asset_path: ./target/dist/cql-stress-cassandra-stress
          asset_name: ${{ env.BIN_NAME_CS }}
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset-sb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL_SB }}
          asset_path: ./target/dist/cql-stress-scylla-bench
          asset_name: ${{ env.BIN_NAME_SB }}
          asset_content_type: application/octet-stream
